sudo: required

language: go

go:
    - 1.4.2

services:
  - docker

before_install:
- docker pull golang:1.4.2-cross
- wget https://downloads.giantswarm.io/builder/0.11.0/builder
- chmod +x ./builder
- export PATH=$PATH:$PWD

script:
- make all
- make run-tests
